============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-6.2.5, py-1.10.0, pluggy-0.13.0
rootdir: /home/shay/a/kim4810/ECE30861/ece30861-team9
plugins: colcon-core-0.20.0, cov-3.0.0
collected 22 items

tests/test_classify.py ........                                          [ 36%]
tests/test_hf_id.py ....F

=================================== FAILURES ===================================
___________ test_hf_id_bad[https://huggingface.co/datasets/foo/bar] ____________

u = 'https://huggingface.co/datasets/foo/bar'

    @pytest.mark.parametrize("u", [
        "https://huggingface.co/datasets/foo/bar",
        "https://example.com/x/y",
        "not a url",
    ])
    def test_hf_id_bad(u):
>       with pytest.raises(Exception):
E       Failed: DID NOT RAISE <class 'Exception'>

tests/test_hf_id.py:19: Failed

---------- coverage: platform linux, python 3.10.12-final-0 ----------
Name                       Stmts   Miss  Cover   Missing
--------------------------------------------------------
src/__init__.py                0      0   100%
src/metrics_framework.py     314    314     0%   2-580
src/scoring.py                35      9    74%   35, 39, 64-74
src/url/__init__.py            0      0   100%
src/url/classify.py           14      0   100%
src/url/ndjson_writer.py      75     75     0%   2-177
src/url/router.py             37     22    41%   50-51, 55-73, 76-81
src/url/url_main.py           80     80     0%   77-203
--------------------------------------------------------
TOTAL                        555    500    10%

=========================== short test summary info ============================
FAILED tests/test_hf_id.py::test_hf_id_bad[https://huggingface.co/datasets/foo/bar]
!!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!
========================= 1 failed, 12 passed in 0.21s =========================
